import z from 'zod';
import { createHttpErrorSchemaFactory } from './http-error-factory';

export const badRequestErrors = createHttpErrorSchemaFactory({
	status: 400,
	codes: [
		'BAD_REQUEST_ERROR',
		'SAME_EMAIL_ERROR',
		'PROFILE_ALREADY_EXISTS',
		'TERMS_NOT_ACCEPTED',
		'PRIVACY_POLICY_NOT_ACCEPTED',
		'EMPTY_CART',
		'CART_QUANTITY_ZERO_ERROR',
		'CART_ITEM_DOES_NOT_BELONG_SELECT_MARKET',
		'CART_HAS_NO_SHIPPABLE_PRODUCTS',
		'INVALID_CHECKOUT_AMOUNT',
		'BLING_TOKEN_REFRESH_FAILED',
		'BLING_CREATE_CONTACT_FAILED',
		'BLING_CREATE_SALES_ORDER_FAILED',
		'BLING_SYNC_ORDER_NOT_PAID',
		'BLING_ORDER_SYNC_FAILED',
		'BLING_ORDER_SYNC_NOT_CLAIMED',
		'BLING_PRODUCT_NOT_FOUND',
		'BLING_DUPLICATED_CONTACT_NOT_FOUND',
		'MELHOR_ENVIO_TOKEN_REFRESH_FAILED',
		'MELHOR_ENVIO_INVALID_OAUTH_STATE',
		'MELHOR_ENVIO_AUTHENTICATION_FAILED',
		'MELHOR_ENVIO_SHIPPING_QUOTE_FAILED',
		'ORDER_SNAPSHOT_INCOMPLETE',
		'ORDER_CUSTOMER_SNAPSHOT_NOT_FOUND',
		'ORDER_SHIPPING_ADDRESS_SNAPSHOT_NOT_FOUND',
		'SHIPPING_MARKET_NOT_SUPPORTED',
		'SHIPPING_NO_RATES_AVAILABLE',
		'SHIPPING_QUOTE_EXPIRED',
		'NO_SHIPPING_RATES_AVAILABLE',
		'SHIPPING_RATE_MARKET_MISMATCH',
		'SHIPPING_RATE_CART_MISMATCH',
		'SHIPPING_RATE_DESTINATION_MISMATCH',
		'CHECKOUT_SHIPPING_RATE_CHANGED',
	],
	defaultCode: 'BAD_REQUEST_ERROR',
});

type Code = z.infer<typeof badRequestErrors.codeSchema>;
export type Code400Identifiers = Code;

export class BadRequestError extends Error {
	readonly code: Code;

	constructor(message?: string, code?: Code) {
		super(message ?? 'Bad Request Error');
		this.code = code ?? 'BAD_REQUEST_ERROR';
		this.name = 'BadRequestError';

		Object.setPrototypeOf(this, BadRequestError.prototype);
	}
}
